import { achievementSchema } from "@/lib/validation/progression";
import type { Achievement } from "@/types/progression";

/** SQL seed and offline mode use the same reviewed rules. */
export const achievements: readonly Achievement[] = [
  {
    id: "first-step",
    name: "일단 해본 자",
    emoji: "🌱",
    description: "첫 미션 완료",
    conditionType: "completed_count",
    conditionValue: { target: 1, filter: {} },
    active: true,
  },
  {
    id: "out-the-door",
    name: "집 밖으로 나오는 데 성공한 자",
    emoji: "🚶",
    description: "야외 미션 1회 완료",
    conditionType: "completed_count",
    conditionValue: { target: 1, filter: { outdoor: true } },
    active: true,
  },
  {
    id: "home-player",
    name: "집에서도 잘 노는 자",
    emoji: "🏠",
    description: "집 카테고리 미션 3회 완료",
    conditionType: "completed_count",
    conditionValue: { target: 3, filter: { category: "home" } },
    active: true,
  },
  {
    id: "snack-sommelier",
    name: "간식 소믈리에",
    emoji: "🍿",
    description: "음식 미션 3회 완료",
    conditionType: "completed_count",
    conditionValue: { target: 3, filter: { category: "food" } },
    active: true,
  },
  {
    id: "friend-adventurer",
    name: "친구와 딴짓에 진심인 자",
    emoji: "🎲",
    description: "친구와 미션 3회 완료",
    conditionType: "completed_count",
    conditionValue: { target: 3, filter: { relationship: "friend" } },
    active: true,
  },
  {
    id: "date-rescuer",
    name: "데이트 고갈을 극복한 자",
    emoji: "💜",
    description: "연인과 미션 1회 완료",
    conditionType: "completed_count",
    conditionValue: { target: 1, filter: { relationship: "couple" } },
    active: true,
  },
  {
    id: "family-memory",
    name: "가족의 추억 수집가",
    emoji: "📸",
    description: "가족과 미션 1회 완료",
    conditionType: "completed_count",
    conditionValue: { target: 1, filter: { relationship: "family" } },
    active: true,
  },
  {
    id: "zero-budget",
    name: "0원으로 놀 줄 아는 자",
    emoji: "🪙",
    description: "실제 사용 금액 0원으로 3회 완료",
    conditionType: "completed_count",
    conditionValue: { target: 3, filter: { zeroCost: true } },
    active: true,
  },
  {
    id: "curious-player",
    name: "호기심 수집가",
    emoji: "🧭",
    description: "서로 다른 카테고리 5개 완료",
    conditionType: "distinct_categories",
    conditionValue: { target: 5, filter: {} },
    active: true,
  },
].map((value) => achievementSchema.parse(value));
