import { writeFileSync } from "node:fs";
import { missions } from "../seed/missions";

const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
const rows = missions
  .map((m) => `(${quote(m.id)}, ${quote(JSON.stringify(m))}::jsonb)`)
  .join(",\n");
const relations = missions
  .flatMap((m) =>
    m.allowedRelationships.map((r) => `(${quote(m.id)}, ${quote(r)})`),
  )
  .join(",\n");
const sql = `-- Generated by npm run db:seed:generate. Edit seed/*.ts, not this file.\n-- No sessions or user records are removed.\nbegin;\ninsert into public.missions(id, template) values\n${rows}\non conflict(id) do update set template = excluded.template;\ndelete from public.mission_relationships where mission_id in (${missions.map((m) => quote(m.id)).join(", ")});\ninsert into public.mission_relationships(mission_id, relationship_type) values\n${relations};\ncommit;\n`;
writeFileSync(
  new URL(
    "../supabase/migrations/202610060002_seed_missions.sql",
    import.meta.url,
  ),
  sql,
);
console.log(`Generated ${missions.length} reviewed mission templates.`);
