import { writeFileSync } from "node:fs";
import { achievements } from "../seed/achievements";
import { missions } from "../seed/missions";

const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
const rows = achievements
  .map(
    (a) =>
      `(${quote(a.id)},${quote(a.name)},${quote(a.emoji)},${quote(a.description)},${quote(a.conditionType)},${quote(JSON.stringify(a.conditionValue))}::jsonb,${a.active})`,
  )
  .join(",\n");
const rewards = missions
  .map((m) => `(${quote(m.id)},${m.baseExp})`)
  .join(",\n");
const sql = `-- Generated by npm run db:progression:generate. Edit seed/achievements.ts and reward policy.\n-- Existing session snapshots and already awarded EXP are preserved.\nbegin;\ninsert into public.achievements(id,name,emoji,description,condition_type,condition_value,active) values\n${rows}\non conflict(id) do update set name=excluded.name,emoji=excluded.emoji,description=excluded.description,condition_type=excluded.condition_type,condition_value=excluded.condition_value,active=excluded.active;\nupdate public.missions m set template=jsonb_set(m.template,'{baseExp}',to_jsonb(r.exp))\nfrom (values\n${rewards}\n) as r(id,exp) where m.id=r.id;\n-- Backfill titles from real DB completions; local archives do not qualify.\ndo $$ declare owner_id uuid; begin\n  for owner_id in select id from public.profiles where merged_into is null loop\n    perform public.award_achievements(owner_id);\n  end loop;\nend; $$;\ncommit;\n`;
writeFileSync(
  new URL(
    "../supabase/migrations/202610070003_progression_seed.sql",
    import.meta.url,
  ),
  sql,
);
console.log(
  `Generated ${achievements.length} titles and ${missions.length} template rewards.`,
);
