-- Generated by npm run db:progression:generate. Edit seed/achievements.ts and reward policy.
-- Existing session snapshots and already awarded EXP are preserved.
begin;
insert into public.achievements(id,name,emoji,description,condition_type,condition_value,active) values
('first-step','일단 해본 자','🌱','첫 미션 완료','completed_count','{"target":1,"filter":{}}'::jsonb,true),
('out-the-door','집 밖으로 나오는 데 성공한 자','🚶','야외 미션 1회 완료','completed_count','{"target":1,"filter":{"outdoor":true}}'::jsonb,true),
('home-player','집에서도 잘 노는 자','🏠','집 카테고리 미션 3회 완료','completed_count','{"target":3,"filter":{"category":"home"}}'::jsonb,true),
('snack-sommelier','간식 소믈리에','🍿','음식 미션 3회 완료','completed_count','{"target":3,"filter":{"category":"food"}}'::jsonb,true),
('friend-adventurer','친구와 딴짓에 진심인 자','🎲','친구와 미션 3회 완료','completed_count','{"target":3,"filter":{"relationship":"friend"}}'::jsonb,true),
('date-rescuer','데이트 고갈을 극복한 자','💜','연인과 미션 1회 완료','completed_count','{"target":1,"filter":{"relationship":"couple"}}'::jsonb,true),
('family-memory','가족의 추억 수집가','📸','가족과 미션 1회 완료','completed_count','{"target":1,"filter":{"relationship":"family"}}'::jsonb,true),
('zero-budget','0원으로 놀 줄 아는 자','🪙','실제 사용 금액 0원으로 3회 완료','completed_count','{"target":3,"filter":{"zeroCost":true}}'::jsonb,true),
('curious-player','호기심 수집가','🧭','서로 다른 카테고리 5개 완료','distinct_categories','{"target":5,"filter":{}}'::jsonb,true)
on conflict(id) do update set name=excluded.name,emoji=excluded.emoji,description=excluded.description,condition_type=excluded.condition_type,condition_value=excluded.condition_value,active=excluded.active;
update public.missions m set template=jsonb_set(m.template,'{baseExp}',to_jsonb(r.exp))
from (values
('photo-time',100),
('three-colors',100),
('one-song',100),
('object-museum',100),
('movie-title',100),
('tiny-advert',120),
('five-questions',100),
('family-memory',100),
('compliment',100),
('tiny-tidy',100),
('silly-story',100),
('photo-theme',100),
('nearby-walk',100),
('snack-pick',100),
('menu-swap',100),
('future-postcard',100),
('book-chapter',100),
('playlist-walk',100),
('cafe-photo-sort',100),
('local-sign-discovery',100),
('online-gallery',100),
('window-weather',100),
('no-heat-snack',100),
('one-line-drawing',100),
('park-bench',100),
('gentle-stretch',100),
('random-word-cover',120),
('friend-small-gift',100),
('friend-photo-theme',100),
('friend-coin-walk',100),
('friend-paper-game',100),
('friend-playlist-exchange',100),
('friend-genre-roulette',100),
('friend-description-draw',100),
('friend-snack-review',100),
('friend-quiet-charades',120),
('friend-one-minute-news',120),
('friend-block-explore',100),
('couple-menu-date',100),
('couple-window-shopping',100),
('couple-portrait',100),
('couple-new-neighborhood',100),
('couple-dessert',100),
('couple-photo-booth',100),
('couple-future-date',100),
('couple-memory-walk',100),
('couple-radio',120),
('couple-small-thanks',100),
('couple-no-heat-duel',100),
('family-photo-album',100),
('family-food-vote',100),
('family-small-walk',100),
('family-photo-theme',100),
('family-taste-quiz',100),
('family-pantry-chef',100),
('family-tidy-relay',100),
('family-drawing-chain',100),
('family-playlist',100),
('family-library-explore',100),
('family-living-room-trip',120)
) as r(id,exp) where m.id=r.id;
-- Backfill titles from real DB completions; local archives do not qualify.
do $$ declare owner_id uuid; begin
  for owner_id in select id from public.profiles where merged_into is null loop
    perform public.award_achievements(owner_id);
  end loop;
end; $$;
commit;
